package_rename_config:
  android:
    app_name: Status Saver
    package_name: com.devzeal.status_saver

  ios:
    app_name: Status Saver
    bundle_name: Status Saver
    package_name: com.devzeal.status_saver

web:
  app_name: Status Saver
  description: Status Saver Web App
