name: whatsapp_status_saver
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  intl: any
  permission_handler: ^12.0.1
  scan_media:
    git:
      url: https://github.com/alihamza0173/scan_media
      ref: master
  share_plus: ^12.0.1
  shared_preferences: ^2.3.2
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.10.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
